### ISSUE TITLE
Bug in Convert Decimal to Hex

### ISSUE THREAD

**Issue by narongporn** [51bit/SmartTools#1]
First of all, thanks for development of SmartTools extension.
I just introduce it to my students and we found bug in converting decimal to Hex.
For example, convert 16 to hex should return 0x10, but the result is 0x01.
Hope you can fix it.

Best regards,
Naronpgorn L.

**Comment by dsssssssss9** [comment]
any idea when this will be fixed please?

**Comment by dsssssssss9** [comment]
any idea when this will be fixed please?

**Comment by xuefengedu** [comment]
Fixed in https://github.com/51bit/SmartTools/releases/tag/v0.3.4.
