### ISSUE TITLE
Bump for problem in convert decimal to hex

### ISSUE THREAD

**Issue by dsssssssss9** [51bit/SmartTools#2]
The convert decimal to hex feature has a problem ....

for example converting 16 decimal to hex ...

Convert 16 Decimal returns 0x01 not 0x10

Any way you can find the time to sort this out please

**Comment by xuefengedu** [comment]
Fixed in https://github.com/51bit/SmartTools/releases/tag/v0.3.4.

**Comment by dsssssssss9** [comment]
Thank you so much for solving this issue 

Very much appreciated

**Comment by dsssssssss9** [comment]
Thank you for fixing this 

Very much appreciated

Regards

Jason 

On 31 July 2021 03:07:58 BST, Xuefeng education ***@***.***> wrote:
>Closed #2.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/51bit/SmartTools/issues/2#event-5093908403

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
